# Generated by Django 2.2.18 on 2021-02-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('name', 'caption', 'url'), name='UniqueConstraint'),
        ),
    ]
